# Generated by Django 5.2.8 on 2025-11-20 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoKafka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calificacion', models.IntegerField()),
                ('instrumento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('instrumento', models.CharField(max_length=50, verbose_name='Instrumento')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor histórico')),
            ],
            options={
                'db_table': 'CALIFICACION',
                'indexes': [models.Index(fields=['instrumento'], name='CALIFICACIO_instrum_a4e4ba_idx'), models.Index(fields=['fecha_pago'], name='CALIFICACIO_fecha_p_c152cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalificacionFactor',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factor', models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(38)], verbose_name='Número de factor')),
                ('valor_factor', models.DecimalField(decimal_places=8, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Valor del factor')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='miapp.calificacion')),
            ],
            options={
                'db_table': 'CALIFICACION_FACTOR',
                'indexes': [models.Index(fields=['calificacion'], name='CALIFICACIO_calific_1f7e00_idx'), models.Index(fields=['numero_factor'], name='CALIFICACIO_numero__34f51f_idx')],
                'unique_together': {('calificacion', 'numero_factor')},
            },
        ),
    ]
